# -*- coding: utf-8 -*-
"""realfind.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TkjraMFLzjcPPKxgZVytJrRE6TJdI3ed
"""

from google.colab import drive
drive.mount("/content/drive")

import os
os.chdir("/content/drive/My Drive/bh/forsk_project")

from twitter_api import get_posts

name="ifyouseekjesse"
number=50

posts=get_posts(name,number)

print(get_posts(name,number))

from function import prediction_string,final_output

print(final_output(posts))

from server import home

